apiVersion: batch/v1
kind: CronJob
metadata:
  name: moodle-test-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: moodle-test-cron
            image: learninghubmoodlecrtest.azurecr.io/learninghubmoodlecronimage:latest
            imagePullPolicy: IfNotPresent
            args: [ "dotnet", "Learninghub-Moodle-cron.dll"]
          restartPolicy: OnFailure